apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-envs
spec:
  generators:
  - git:
      repoURL: https://github.com/nikita-akuity/grafana-delivery.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: 'grafana-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/nikita-akuity/grafana-delivery.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: http://cluster-cluster-2:8001
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - createNamespace=true
