apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret-files
  namespace: grafana
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: grafana-secret-files
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        datasource.yaml: |
          datasources:
          - name: Graphite
            type: graphite
            access: proxy
            url: http://localhost:8080
            password: "{{ .password }}"
            user: "{{ .user }}"

  data:
  - secretKey: user
    remoteRef:
      key: /demo/grafana/admin-user
      version: v1
  - secretKey: password
    remoteRef:
      key: /demo/grafana/admin-password
      version: v1
